"""add audit logs table

Revision ID: 120cb49ea4a3
Revises: 0002_add_mlflow_status_fields
Create Date: 2026-04-29 00:34:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '120cb49ea4a3'
down_revision: Union[str, None] = '0002_add_mlflow_status_fields'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic ###
    op.create_table('audit_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('request_id', sa.String(length=64), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('user', sa.String(length=256), nullable=True),
    sa.Column('endpoint', sa.String(length=256), nullable=False),
    sa.Column('method', sa.String(length=16), nullable=False),
    sa.Column('payload_hash', sa.String(length=64), nullable=True),
    sa.Column('result', sa.String(length=32), nullable=False),
    sa.Column('status_code', sa.String(length=16), nullable=True),
    sa.Column('audit_metadata', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_request_id'), 'audit_logs', ['request_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic ###
    op.drop_index(op.f('ix_audit_logs_request_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
