"""Audit logging middleware for tracking mutations."""

from __future__ import annotations

import hashlib
import json
import logging
import time
from collections.abc import Awaitable, Callable
from typing import Any

from fastapi import Request
from sqlalchemy.ext.asyncio import AsyncSession
from starlette.responses import Response

from ares.db import crud
from ares.observability.metrics import audit_write_failures_total

log = logging.getLogger(__name__)

SENSITIVE_KEYS = {"password", "secret", "token", "api_key"}


def _redact_payload(payload: Any) -> Any:
    if isinstance(payload, dict):
        return {
            key: "[REDACTED]" if str(key).lower() in SENSITIVE_KEYS else _redact_payload(value)
            for key, value in payload.items()
        }
    if isinstance(payload, list):
        return [_redact_payload(item) for item in payload]
    return payload


async def log_audit_event(
    db: AsyncSession,
    request_id: str,
    user: str | None,
    endpoint: str,
    method: str,
    payload: dict[str, Any] | None,
    result: str,
    status_code: int | None,
    audit_metadata: dict[str, Any] | None = None,
    api_key_id: str | None = None,
    actor_type: str | None = None,
    resource_type: str | None = None,
    resource_id: str | None = None,
    action: str | None = None,
    correlation_id: str | None = None,
    error_code: str | None = None,
    duration_ms: float | None = None,
) -> None:
    """Log an audit event to the database."""
    payload_hash = None
    if payload:
        payload_str = json.dumps(payload, sort_keys=True)
        payload_hash = hashlib.sha256(payload_str.encode()).hexdigest()[:64]
    await crud.create_audit_log(
        db,
        request_id=request_id,
        user=user or "anonymous",
        endpoint=endpoint,
        method=method,
        payload_hash=payload_hash,
        result=result,
        status_code=status_code,
        audit_metadata=audit_metadata or {},
        api_key_id=api_key_id,
        actor_type=actor_type,
        resource_type=resource_type,
        resource_id=resource_id,
        action=action,
        correlation_id=correlation_id,
        error_code=error_code,
        duration_ms=duration_ms,
    )
    await db.commit()


class AuditMiddleware:
    """Middleware to log all mutation requests."""
    
    def __init__(self, db_session_factory: Callable[[], Any]) -> None:
        self.db_session_factory = db_session_factory

    async def _safe_log_audit_event(self, **kwargs: Any) -> None:
        try:
            async with self.db_session_factory() as db:
                await log_audit_event(db=db, **kwargs)
        except Exception as exc:
            audit_write_failures_total.inc()
            log.warning("audit_log_write_failed", exc_info=exc)
    
    async def __call__(
        self,
        request: Request,
        call_next: Callable[[Request], Awaitable[Response]],
    ) -> Response:
        """Process request and log mutation events."""
        try:
            from ares.db.session import get_db

            if get_db in getattr(request.app, "dependency_overrides", {}):
                return await call_next(request)
        except Exception:
            pass
        # Reuse the request ID generated by the global request middleware when available.
        request_id = getattr(request.state, "request_id", None)
        if request_id is None:
            import uuid

            request_id = str(uuid.uuid4())
        request.state.request_id = request_id
        
        # Only log mutations (POST, PUT, DELETE, PATCH)
        if request.method in {"POST", "PUT", "DELETE", "PATCH"}:
            started = time.perf_counter()
            user = request.headers.get("x-user-id")
            authorization = request.headers.get("authorization")
            api_key_header = request.headers.get("x-api-key")
            principal = getattr(request.state, "principal", None)
            api_key_id = getattr(principal, "key_id", None)
            actor_type = "api_key" if api_key_id else "header" if user else "anonymous"
            path_parts = [part for part in request.url.path.split("/") if part]
            resource_type = path_parts[2] if len(path_parts) >= 3 and path_parts[0] == "api" else (path_parts[0] if path_parts else None)
            resource_id = path_parts[3] if len(path_parts) >= 4 else None
            action = path_parts[-1] if path_parts else request.method.lower()
            correlation_id = request.headers.get("x-correlation-id") or request_id
            payload = None
            try:
                # Get payload if available
                if request.method in {"POST", "PUT", "PATCH"}:
                    try:
                        payload = await request.json()
                    except Exception:
                        payload = None
                redacted_payload = _redact_payload(payload) if payload is not None else None
                audit_metadata: dict[str, Any] = {"headers": {}}
                if authorization is not None:
                    audit_metadata["headers"]["Authorization"] = "[REDACTED]"
                if api_key_header is not None:
                    audit_metadata["headers"]["X-API-Key"] = "[REDACTED]"
                if redacted_payload is not None:
                    audit_metadata["payload"] = redacted_payload
                
                # Process request
                response = await call_next(request)
                
                # Log successful mutation
                await self._safe_log_audit_event(
                    request_id=request_id,
                    user=user,
                    endpoint=str(request.url.path),
                    method=request.method,
                    payload=redacted_payload,
                    result="success",
                    status_code=response.status_code,
                    audit_metadata=audit_metadata,
                    api_key_id=api_key_id,
                    actor_type=actor_type,
                    resource_type=resource_type,
                    resource_id=resource_id,
                    action=action,
                    correlation_id=correlation_id,
                    duration_ms=(time.perf_counter() - started) * 1000,
                )
                
                return response
            except Exception as e:
                # Log failed mutation
                await self._safe_log_audit_event(
                    request_id=request_id,
                    user=user,
                    endpoint=str(request.url.path),
                    method=request.method,
                    payload=redacted_payload,
                    result="error",
                    status_code=None,
                    audit_metadata={**audit_metadata, "error": str(e)},
                    api_key_id=api_key_id,
                    actor_type=actor_type,
                    resource_type=resource_type,
                    resource_id=resource_id,
                    action=action,
                    correlation_id=correlation_id,
                    error_code=getattr(e, "error_code", None),
                    duration_ms=(time.perf_counter() - started) * 1000,
                )
                raise
        else:
            # Non-mutation requests just pass through
            return await call_next(request)
